### ISSUE TITLE
TypeError: typedi_1.Container.registerPropertyHandler is not a function

### ISSUE THREAD

**Issue by booradleys** [typeorm/typeorm-typedi-extensions#12]
Hi there,
I've got this following error:

C:\Applications\Node\exotica\server>node app.js
C:\Applications\Node\exotica\server\node_modules\typeorm-typedi-extensions\decorators\OrmCustomRepository.js:23
            typedi_1.Container.registerPropertyHandler({ target: target /* todo: looks like typedi wrong type here */, key: propertyName, getValue: ge
tValue });
                               ^

TypeError: typedi_1.Container.registerPropertyHandler is not a function
    at C:\Applications\Node\exotica\server\node_modules\typeorm-typedi-extensions\decorators\OrmCustomRepository.js:23:32
    at DecorateProperty (C:\Applications\Node\exotica\server\node_modules\reflect-metadata\Reflect.js:530:29)
    at Object.decorate (C:\Applications\Node\exotica\server\node_modules\reflect-metadata\Reflect.js:100:20)
    at __decorate (C:\Applications\Node\exotica\server\dist\repository\TCandidatStatsRepository.js:4:92)
    at Object.<anonymous> (C:\Applications\Node\exotica\server\dist\repository\TCandidatStatsRepository.js:47:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

David

**Comment by booradleys** [comment]
Error disapeared with last commit:
npm install typeorm-typedi-extensions --save-dev
