### ISSUE TITLE
"Cannot get reflected type for a "undefined" method's 1. parameter"

### ISSUE THREAD

**Issue by ryuuji3** [typeorm/typeorm-typedi-extensions#28]
I'm trying to get my jest unit test to work, but it keeps on failing with this error message. 
Here's the error message in more detail:
```
Cannot get reflected type for a "undefined" method's 1. parameter of Function class. Make sure you have turned on an "emitDecoratorMetadata": true, option in tsconfig.json. and that you have imported "reflect-metadata" on top of the main entry file in your application.And make sure that you have annotated the property type correctly with: Repository, MongoRepository, TreeRepository or custom repository class type.

       7 | @Service()
       8 | export class UserService {
    >  9 |   constructor(@InjectRepository() public readonly repository: UserRepository) {}
         |                                    ^
      10 | 
      11 |   public register = async (user: User) => this.repository.save(user)
      12 | 

      at new ParamTypeMissingError (server/node_modules/typeorm-typedi-extensions/errors/ParamTypeMissingError.js:16:28)
      at server/node_modules/typeorm-typedi-extensions/decorators/InjectRepository.js:49:23
      at server/src/services/user.service.ts:9:36
      at DecorateConstructor (server/node_modules/reflect-metadata/Reflect.js:541:33)
      at Object.decorate (server/node_modules/reflect-metadata/Reflect.js:130:24)
      at Object.<anonymous>.__decorate (server/src/services/user.service.ts:4:92)
      at server/src/services/user.service.ts:98:19
      at Object.<anonymous> (server/src/services/user.service.ts:103:2)
      at Object.<anonymous> (server/src/services/user.spec.ts:40:22)
```

Here's my test code that is failing:
```ts
beforeAll(async () => {
      user.username = username
      await user.setPassword(validPassword)

      MockRepository.mockImplementation(() => ({
        findOne: jest.fn(({ username }) => {
          if (username === 'test@example.com') {
            return user
          } else {
            return undefined
          }
        }),
      }))
      repository = new MockRepository()
      service = new UserService(repository) // this is where the fail happens
    })
```

My repository:
```ts
@Service()
@EntityRepository(User)
export class UserRepository extends Repository<User> {}
```

My service class:
```ts
@Service('user.service')
export class UserService {
  constructor(@InjectRepository() public readonly repository: UserRepository) {}
}
```

I do have import reflect-metadata, emitMetdata, etc. all setup so I'm confused. I would have thought that passing in a value to the constructor would bypass InjectRepository(). 
Of note, removing the @InjectRepository annotation removes the jest error. 
Also, with the InjectRepository annotation, and when I start the server, it works just fine.

So the fact that there is no container is the problem, I guess, but I shouldn't have to set one up for a unit test?

I was using an older version of typeorm-typedi-extensions and it worked fine, but when I downgraded from the latest, it did not work either. So, not sure what changed...

**Comment by ryuuji3** [comment]
I did some more digging and I think it is more to do with how jest interacts with typescript,
so sorry I'll just go ahead and close this.

**Comment by MarZab** [comment]
In my case, the repository was not yet resolved since the order of imports was wrong.
