### ISSUE TITLE
Getting error "Unexpected token =" when injecting

### ISSUE THREAD

**Issue by popstr** [typeorm/typeorm-typedi-extensions#7]
I am having issues with injecting TypeORM connection, getting the unhelpful error message "SyntaxError: Unexpected token =".

Here is a typescript file to reproduce the error. I am running this using the latest ts-node, 2.1.0.

```typescript
import 'reflect-metadata';
import { Container, Inject } from 'typedi';
import { OrmConnection } from 'typeorm-typedi-extensions';
import { useContainer, createConnection, Connection, ConnectionOptions } from 'typeorm';

class App {
	@OrmConnection()
	connection: Connection;

	go() {
		console.log('connection', this.connection);
	}
}

useContainer(Container);

const options: ConnectionOptions = {
	driver: {
		type: 'mysql',
		host: 'localhost',
		port: 3306,
		username: 'develop',
		password: '...',
		database: 'mydb'
	},
	entities: []
};
createConnection(options).then(() => {
	const app: App = Container.get(App);
	app.go();
});
```

This prints:
```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/var/www/project/src/index.ts:1:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
error Command failed with exit code 1.
```

Am I doing something wrong?

**Comment by pleerock** [comment]
I guess you have old version of node. Try to upgrade node version?

**Comment by popstr** [comment]
You're absolutely right. I was running node version 4. Switching to 6 or 7 fixes the problem.
Closing issue.
